UpgradeClientsBase feat(client-base): intermidiate commit #1
ivancupchick/zubrAuto pull request #15
Opened 2024-08-26 12:32 UTC by AndrewNovik

First visible table with data. Waiting for review

2024-09-06 14:43 UTC, ivancupchick requested changes

2024-09-06 14:43 UTC, ivancupchick commented on ui/src/app/pages/za-settings/pages/clients-base/clients-base.component.ts
> +    return this.fieldService.getFieldsByDomain(FieldDomains.Client).subscribe(res => this.fieldConfigs = res);
.pipe(takeUntil(this.destoyed))

2024-09-06 14:43 UTC, ivancupchick commented on ui/src/app/pages/za-settings/pages/clients-base/clients-base.component.ts
> +  filter(){
`onFilter` + return type for all functgion please  f.e. `foo(): void { ... }`

2024-09-06 14:43 UTC, ivancupchick commented on ui/src/app/pages/za-settings/pages/clients-base/clients-base.component.ts
> +    let filters = skipEmptyFilters({...this.form.value });
`let filters = skipEmptyFilters({...structuredClone(this.form.value) });`

2024-09-06 14:43 UTC, ivancupchick commented on ui/src/app/pages/za-settings/pages/clients-base/clients-base.component.ts
> +        filters = { 'createdDate': Date.parse(date[0]), ...rest }
Where `'filter-operator-createdDate'` for one ?

2024-09-06 14:43 UTC, ivancupchick commented on ui/src/app/pages/za-settings/pages/clients-base/clients-base.component.ts
> +        specialists: this.specialists // Всех выводить или мб аваибл специалистов только?
See in old clients component or in client-next-action-dashlet how

2024-09-06 14:43 UTC, ivancupchick commented on ui/src/app/pages/za-settings/pages/clients-base/services/client-base-data.service.ts
> +  specialists: ServerUser.Response[] = [];
?

2024-09-06 14:43 UTC, ivancupchick commented on ui/src/app/pages/za-settings/pages/clients-base/services/client-base-data.service.ts
> +  fieldConfigs: ServerField.Response[] = [];
?

2024-09-11 19:35 UTC, ivancupchick requested changes

2024-09-11 19:35 UTC, ivancupchick commented on ui/src/app/pages/za-settings/pages/clients-base/services/client-base-data.service.ts
> +    this.destroy$.complete();
for whar?

2024-09-11 19:35 UTC, ivancupchick commented on ui/src/app/pages/za-settings/shared/pageagle-grid/pageagle-grid.component.ts
> +  @Input() initialPageFilters!: string[];
wrong name

2024-09-11 19:35 UTC, ivancupchick commented on ui/src/app/pages/za-settings/pages/clients-base/clients-base.component.ts
> +      if (date[0] !== date[1]) {
23:59 for date[1]
00:01 for date[0]

2024-09-11 19:35 UTC, ivancupchick commented on ui/src/app/pages/za-settings/pages/clients-base/clients-base.component.ts
> +    this.clientBaseService.updatePage(filters);
probably need to add 
this.first = 0 , don't?

2024-09-11 19:35 UTC, ivancupchick commented on ui/src/app/pages/za-settings/pages/clients-base/clients-base.component.ts
> +    this.destoyed.complete();
for what

2024-09-11 19:35 UTC, ivancupchick commented on ui/src/app/pages/za-settings/pages/clients-base/services/client-base-data.service.ts
> +
empty

2024-09-11 19:35 UTC, ivancupchick commented on ui/src/app/pages/za-settings/pages/clients-base/clients-base.component.html
> +          <p-button size="small" label="Filter" type="submit" (onClick)="filter()" class="mr-2">
Filter -> Получить

2024-09-11 19:35 UTC, ivancupchick commented on ui/src/app/pages/za-settings/pages/clients-base/clients-base.component.html
> +          <p-button size="small" type="button" label="Clear" (onClick)="clearFilters()" class="mr-2">
Clear -> Очистить

2024-09-11 19:35 UTC, ivancupchick commented on ui/src/app/pages/za-settings/pages/clients-base/clients-base.component.ts
> +  specialistList: {name: string, value: string}[] = [];
order: 
@Input's
@Output's

readonly variables

other variables

Observable variables with $ symbol

2024-09-11 19:35 UTC, ivancupchick commented on ui/src/app/pages/za-settings/pages/clients-base/services/client-base-data.service.ts
> +  };
replace in begging

2024-09-13 10:53 UTC, AndrewNovik commented on ui/src/app/pages/za-settings/pages/clients-base/clients-base.component.ts
> +      if (date[0] !== date[1]) {
немного по своему исправил. Не понял как с форматом работать

2025-04-17 19:34 UTC, ivancupchick approved these changes

2025-04-17 19:34 UTC, merged